### ISSUE TITLE
Undefined variable

### ISSUE THREAD

**Issue by Vatvat99** [jagilpe/ajax-modals-bundle#1]
I have this error in chrome console : 
Uncaught ReferenceError: button is not defined
    at Plugin._updateButtonsStatus (jgp-modal-dialog.js:276)

I fixed it on my computer by adding the var keyword on line 276 in Resources/js/jgp-modal-dialog.js :
for (`var` button in this.dialogData.buttons) {

**Comment by ghost** [comment]
Hi @Vatvat99, thank you for the notice. I've added it and published a new release. If you update to 1.0.1 the error should be gone.
